import { Part, Type } from "@google/genai";
import { LessonPlan, SLO } from "../../types";
import { cleanAndParseJson } from '../jsonHelpers';
import { sanitizeStringFields } from '../latexSanitizer';
import { LogCallback } from './types';
import { requestJsonWithRetry } from './client';

export function parseLessonPlanJson(jsonText: string, gradeLevel: string, subject: string): LessonPlan {
  try {
    const parsed = cleanAndParseJson(jsonText);
    if (!parsed.title || !parsed.objective || !Array.isArray(parsed.activities) || !parsed.homework) {
      throw new Error("Parsed JSON is missing required fields.");
    }
    const cleaned = sanitizeStringFields(parsed) as Record<string, unknown>;
    return {
      ...(cleaned as unknown as LessonPlan),
      gradeLevel,
      subject,
    };
  } catch (e) {
    console.error("Error parsing lesson plan JSON:", e);
    if (e instanceof Error) {
      throw new Error(`Failed to parse lesson plan JSON: ${e.message}`);
    }
    throw new Error("Failed to parse the lesson plan JSON generated by the model.");
  }
}

export async function generateLessonPlan(
  slo: SLO,
  unitSlos: SLO[],
  contextFileParts?: Part[],
  subjectName?: string,
  logCallback?: LogCallback
): Promise<LessonPlan> {
  const log = (msg: string) => {
    console.log(`[geminiService] ${msg}`);
    logCallback?.(msg);
  };

  const gradeNum = parseInt(slo.grade?.replace(/Grade\s+|Class\s+/i, "") || "9", 10);
  const gradeLevelContext = isNaN(gradeNum) ? `${slo.grade}` : `${slo.grade} (${gradeNum <= 10 ? "Foundational" : "Advanced"})`;
  const subject = subjectName || "General";

  log(`Generating lesson plan for SLO: ${slo.SLO_ID} | Subject: ${subject} | Grade: ${slo.grade}`);

  const systemInstruction = `You are a ${subject} Teacher at Peoples Higher Secondary School Jamshoro, creating a detailed lesson plan for your own use and for school records. Your task is to generate a comprehensive 40-minute lesson plan as a JSON object using the 4As instructional model. The tone should be professional, direct, and suitable for a Pakistani secondary school context.

**The 4As Lesson Plan Structure (Peoples Higher Secondary School Jamshoro Template):**

**A - ACTIVITY (Activating Prior Knowledge)** [5-10 minutes]:
- Engage students with a brief, interactive activity related to the lesson topic
- Connect new content to students' existing knowledge and experiences
- Include specific teacher instructions and expected student responses
- Use questioning techniques, brainstorming, or quick demonstrations

**A - ANALYSIS (Acquiring New Knowledge)** [10-15 minutes]:
- Process the activity and introduce the main concepts
- Present new information clearly with examples relevant to Pakistani students
- Include key definitions, formulas, or principles
- Use questioning and discussion to check understanding
- Provide clear explanations with local context where appropriate

**A - ABSTRACTION (Applying Knowledge - Generalization)** [10-15 minutes]:
- Guide students to generalize and internalize the concept
- Help students identify patterns, principles, or rules
- Connect the lesson to real-life applications in Pakistan
- Summarize key points and clarify misconceptions
- Ensure students can articulate the concept in their own words

**A - APPLICATION (Assessing Knowledge)** [5-10 minutes]:
- Provide a practical task, problem, or assessment activity
- Students apply what they learned to new situations
- Include evaluation criteria or success indicators
- Could be a written exercise, oral questioning, group task, or individual work
- Check for mastery of the lesson objective

**Critical Instructions:**
1.  **Grounded Content:** Base the entire lesson plan ONLY on the attached PDF content if provided. If no PDF, use your knowledge of the ${subject} curriculum for ${slo.grade} as per Sindh Textbook Board (STBB) standards.
2.  **NO SOURCE REFERENCES:** Never mention "the PDF," "textbook," or any source. Present content directly as lesson material.
3.  **Teacher-Centric Tone:** Write in direct instructional style. Use active verbs. Avoid "The teacher will..." or "Students will..." Instead use imperative forms: "Begin by...", "Ask students to...", "Demonstrate...", "Guide learners to...".
4.  **Specific Instructions:** For each activity, provide clear step-by-step teacher actions and anticipated student responses.
5.  **Local Context:** Make examples and applications relevant to Pakistani students, using familiar contexts, names, and scenarios where appropriate.
6.  **Time Allocation:** Each of the 4 activities must have a duration. Total must equal exactly 40 minutes.
7.  **Homework:** Provide a meaningful homework assignment reinforcing the lesson objective, appropriate for Pakistani students.
8.  **MANDATORY JSON OUTPUT:** Output ONLY valid JSON matching the schema. No extra text or markdown.
9.  **EQUATIONS — ONLY for real math, NEVER for text:** Wrap mathematical equations, formulas and expressions in LaTeX delimiters, and NOTHING else:
    - Inline equations use single dollar signs: $E = mc^2$, $PV = nRT$, $F = ma$
    - Display equations use double dollar signs: $$\\frac{3}{2}kT$$
    - Includes fractions (3/2) → $\\frac{3}{2}$, powers v^2 → $v^2$, Greek letters rho → $\\rho$
    - Example: "The equation $P = \\frac{1}{3} \\rho v^2$ relates pressure to density and velocity."
    - FORBIDDEN — ordinary words, names, biological/Latin terms and emphasis must NEVER go inside dollar signs. Wrong: "$Bios$ means life", "study of $cells$", "the plant $Brassica\\ campestris$", "define $biology$". Keep those as plain text; use *asterisks* for emphasis or italics.
10.  **Grade Appropriateness:** Content must match ${gradeLevelContext} cognitive level.
`;

  const lessonPlanSchema = {
    type: Type.OBJECT,
    properties: {
      title: { type: Type.STRING, description: "A concise, specific topic for a 40-minute lesson derived from the main SLO." },
      objective: { type: Type.STRING, description: "A clear restatement of the user's provided SLO, framed as a student learning objective." },
      materials: { type: Type.ARRAY, description: "A list of necessary resources, including textbook pages if possible.", items: { type: Type.STRING } },
      activities: {
        type: Type.ARRAY,
        description: "An array of four activities following the 4As framework: Activity (Activating Prior Knowledge), Analysis (Acquiring New Knowledge), Abstraction (Applying Knowledge/Generalization), and Application (Assessing Knowledge).",
        items: {
          type: Type.OBJECT,
          properties: {
            name: { type: Type.STRING, enum: ['Activity', 'Analysis', 'Abstraction', 'Application'], description: "The 4As phase name." },
            duration: { type: Type.INTEGER, description: "Duration of this activity in minutes." },
            description: { type: Type.STRING, description: "Concise explanation of this phase in 2-4 sentences. Include formulas with variable breakdowns, worked examples, and diagrams/tables described in text. Written in third person." },
          },
          required: ['name', 'duration', 'description'],
        },
      },
      homework: { type: Type.STRING, description: "A brief but meaningful homework assignment that reinforces the lesson's objective." }
    },
    required: ['title', 'objective', 'materials', 'activities', 'homework'],
  };

  const contextText = unitSlos
    .filter((s) => s.uniqueId !== slo.uniqueId)
    .map((s) => `- ${s.SLO_ID}: ${s.SLO_Text}`)
    .join("\n");

  const hasPdf = contextFileParts && contextFileParts.length > 0;

  const userPrompt = `You are generating EXACTLY ONE lesson plan for EXACTLY ONE Student Learning Outcome (SLO). Do NOT create lesson plans for any other SLOs.

**TARGET SLO (the ONLY one to plan for):**
${slo.SLO_ID}: ${slo.SLO_Text}

${hasPdf ? `The attached PDF is the ${subject} textbook chapter for ${slo.grade}. Use its content as the GROUND TRUTH for this lesson plan — base examples, definitions, and activities on what the textbook actually covers for this specific topic.` : `Use your knowledge of the ${subject} curriculum for ${slo.grade} as per STBB standards.`}

For awareness of what else exists in this chapter (DO NOT plan for these, just know they exist):
${contextText || "None"}

Generate a single 40-minute lesson plan focused ONLY on the target SLO above.`;

  const userPromptLength = userPrompt.length;
  const contextPartCount = contextFileParts?.length ?? 0;
  log(`Built user prompt (${userPromptLength} chars). Context PDF parts attached: ${contextPartCount}.`);

  return requestJsonWithRetry<LessonPlan>({
    operationName: "generating lesson plan",
    firstAttemptLog: "Calling Gemini API via withKeyRotation...",
    systemInstruction,
    userPrompt,
    schema: lessonPlanSchema,
    temperature: 0.2,
    contextParts: contextFileParts,
    log,
    parse: (raw) => {
      log(`Received API response (${raw.length} chars). Parsing JSON...`);
      const lessonPlan = parseLessonPlanJson(raw, gradeLevelContext, subject);
      log(`Successfully parsed lesson plan: "${lessonPlan.title}"`);
      return lessonPlan;
    },
    abortIf: (err) => {
      if (err.message.includes("does not support pdf input") || err.message.includes("Cannot read ")) {
        return "PDF_CONTEXT_NOT_SUPPORTED: The current AI model does not support PDF file input.";
      }
      return null;
    },
  });
}
